- name: Add key for repository
  apt_key:
    url: http://nginx.org/keys/nginx_signing.key

- name: Add repository
  apt_repository:
    repo: "deb http://nginx.org/packages/mainline/debian/ {{debian_version}} nginx"

- name: Install Nginx
  apt:
    name: nginx
    update_cache: yes
    cache_valid_time: 3600
