---
- name: Install php packages
  apt: pkg={{ item }} state=latest
  with_items:
    - php5-cli
    - php5-fpm
    - php5-mysqlnd
    - php5-mcrypt
    - php5-gd
    - php5-curl
    - php5-imagick
    - imagemagick
    - php-apcu
