---
- name: Add key for repository
  apt_key:
    url: https://packages.sury.org/php/apt.gpg

- name: Add repository
  apt_repository:
    repo: "deb https://packages.sury.org/php/ {{debian_version}} main"

- name: Install php-fpm and deps
  apt: pkg={{ item }} force=yes state=latest
  with_items:
    - php7.2
    - php7.2-fpm
    - php7.2-cli
    - php7.2-mysql
    - php7.2-gd
    - php7.2-curl
    - php7.2-xml
    - php7.2-mbstring
