---
- name: Install php packages
  apt: pkg={{ item }} state=latest
  with_items:
    - php5-cli
    - php5-fpm
    - php5-mysql
    - php5-mcrypt
    - php5-gd
    - php5-curl
    - php5-imagick
    - imagemagick
    - pgp5-libgd

- name: Disable opcache (conflicts with chrooted env)
  command: mv /etc/php5/fpm/conf.d/05-opcache.ini /etc/php5/fpm/conf.d/05-opcache.ini.disabled
  notify: Restart php5-fpm