---
  - hosts: minimal
    sudo: true
    roles:
      - base
      - cron-apt
      - ntp
      - git
      - ipv4harden
      - ipv6disable

  - hosts: fullapache2
    sudo: true
    roles:
      - base
      - cron-apt
      - ntp
      - git
      - ipv4harden
      - ipv6disable
      - apache
      - php-fpm
      - apache-fastcgi
      - mysql
      - modsecurity
      - fail2ban
      
  - hosts: apache2simple
    sudo: true
    roles:
      - base
      - cron-apt
      - ntp
      - git
      - ipv4harden
      - ipv6disable
      - fail2ban
      - php
      - mysql
      - apache

