---
  - hosts: all
    sudo: true
    user: vlad
    roles:
      - base
      - ntp
      - git
      - mysql
      - logwatch
      - fail2ban
      - nginx
      - php-fpm
      - composer
      - zsh
      - node