---
  - hosts: all
    remote_user: root
    sudo: true
    roles:
      - role: base
        tags: "base"
      - role: ntp
        tags: "ntp"
      - role: git
        tags: "git"
      - role: zsh
        tags: "zsh"
      - role: iptables-persistent
        tags: "iptables-persistent"
      - role: fail2ban
        tags: "fail2ban"
      - role: nginx
        tags: "nginx"
      - role: node
        tags: "node"
