--- 
- name: Checking for previously added repositories
  stat: path=/etc/apt/sources.list.d/oss-binaries_phusionpassenger_com_apt_passenger.list
  register: repos_passenger_present

- name: Add phusionpassenger apt keychain
  apt_key: keyserver='keyserver.ubuntu.com' id='561F9B9CAC40B2F7' state='present'
  when: repos_passenger_present.stat.exists == false

- name: Installing apt-transport-https
  apt: pkg={{ item }} state=latest
  with_items:  
    - apt-transport-https
    - ca-certificates
  when: repos_passenger_present.stat.exists == false

- name: Add phusionpassenger.com repository
  apt_repository: repo='deb https://oss-binaries.phusionpassenger.com/apt/passenger stretch main ' state=present
  when: repos_passenger_present.stat.exists == false

- name: Install passenger
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - passenger

#- name: Install support files to enable nginx recompiling (for passenger)
#  apt: pkg={{ item }} state=latest update_cache=yes
#  with_items:
#    - build-essential
#    - libcurl4-openssl-dev
#    - libssl-dev
#    - zlib1g-dev

- name: Checking for apache2
  stat: path=/etc/apache2/
  register: apache2_present

- name: Install apache2-dev and libapache2-mod-passenger
  apt: pkg={{ item }} state=latest
  with_items:
    - apache2-dev
    - libapache2-mod-passenger
  when: apache2_present.stat.exists == true

- name: Checking for nginx
  stat: path=/etc/nginx/
  register: nginx_present

- name: Install nginx-mod-passenger
  apt: pkg={{ item }} state=latest
  with_items:
    - libnginx-mod-http-passenger
  when: nginx_present.stat.exists == true

