---
- name: Install php packages
  apt: pkg={{ item }} state=latest
  with_items:
    - php-cli
    - libapache2-mod-php
    - php-mysqlnd
    - php-mcrypt
    - php-gd
    - php-curl
    - php-imagick
    - imagemagick
    - php-apcu
